### ISSUE TITLE
Dolby presets not preserving red objects hue

### ISSUE THREAD

**Issue by antonmeleshkevich** [jedypod/open-display-transform#14]
It's most noticeable with 100 nit vs others. But with others it's also noticeable. The more nits - the more red jacket shifts to the orange. Not sure if this an issue or it behaves as it should.
And I apologize for the giant images :) It's probably because they are vertical.

![Screenshot 2021-11-04 053037](https://user-images.githubusercontent.com/34407001/140233308-dee04840-5528-4e7f-b2de-27c8ff82356b.jpg)

![Screenshot 2021-11-04 053051](https://user-images.githubusercontent.com/34407001/140233313-29361f92-8bfc-417b-b2dc-d4260d963494.jpg)

![Screenshot 2021-11-04 053124](https://user-images.githubusercontent.com/34407001/140233317-b2085525-d8ae-4989-bfab-58ac1057903e.jpg)

![Screenshot 2021-11-04 053140](https://user-images.githubusercontent.com/34407001/140233319-bbebfea0-177f-498c-9830-a86448838e52.jpg)

![Screenshot 2021-11-04 053150](https://user-images.githubusercontent.com/34407001/140233322-9ee66a08-978d-4dce-8b34-4e306715d7d1.jpg)

**Comment by jedypod** [comment]
Thanks very much for the bug report @antonmeleshkevich !

I finally got some time to track down what this was coming from and fix it. This commit should fix the issue:
https://github.com/jedypod/open-display-transform/commit/9efc352233b96110e00b48ca87a6aa949d612af8
