### ISSUE TITLE
N6 Value and Vibrance not working in Resolve

### ISSUE THREAD

**Issue by BatmanAK** [jedypod/open-display-transform#18]
Hi, Jedypod, 

I installed the N6 Value and N6 Vibrance dctls into Resolve and when I move the sliders they do nothing at all. Am I missing a step? Thanks for your help!

**Comment by antonmeleshkevich** [comment]
Hi! You most likely didn't copy liblmt.h into the same directory.

**Comment by BatmanAK** [comment]
That worked! Thanks so much.
