### ISSUE TITLE
N6 Crosstalk is simply not working

### ISSUE THREAD

**Issue by robynsun-love** [jedypod/open-display-transform#26]
Hello!

No matter what I do, I cannot get the N6 Crosstalk LMT DCTL to work. None of the UI parameters show up; and in Fusion (where I use thatcherfreeman's DCTL Interpreter Fuse so that I can use DCTLs in Resolve Lite) the node label goes from white to red; as if something is wrong with the code. Looking at said code in a text editor, I can't see anything wrong with it. Perhaps someone else might have better luck?

The other look modification DCTLs work just fine, btw. 

Thanks! :)

**Comment by jedypod** [comment]
Hello! 
Thanks for the opening the issue! It's not much to go on... Would you be able to attach the log file after trying to run the N6Crosstalk DCTL, and also tell me what OS and what version of Resolve you're trying this on?

I did check here and it is compiling and working on Linux in Resolve 19.0b5. I did notice that I included some `0.0f` values in the parameter definitions, which aren't there in the other n6 tools. It's a long shot but if you want to give the attached DCTL a try it might be worth testing if removing those helps (rename .txt to .dctl).
[n6CrossTalk.txt](https://github.com/user-attachments/files/16421367/n6CrossTalk.txt)

**Comment by robynsun-love** [comment]
Ha! The DCTL you just linked _is_ working! Not sure if the code is even different in any way, and yet it's working! Thank you! :)

**Comment by jedypod** [comment]
Wow interesting. It's good to know that `0.0f` style floats in parameter definitions cause issues on some platforms. Can you let me know what operating system this was on?

I've pushed a fix for this, and also a bugfix for another issue I noticed while testing that was causing hue shifts in magenta, blue and cyan to not work as expected.

Thanks for the bug report!

**Comment by robynsun-love** [comment]
This was on Mac OS Monterey 12.0.1.

**Comment by jedypod** [comment]
Awesome, thanks! That's good to know, I'll keep this in mind for the future.

Closing this issue now!
